apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment 
spec: 
  replicas: 4
  selector:
    matchables:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: kadarinandhini/sample:kubeimage1
          ports:
            - containerPort: 5000